//#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
//#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//setMotorSpeed(leftMotor, 50);		//Set the leftMotor (motor1) to half power (50)
	//setMotorSpeed(rightMotor, 50);  //Set the rightMotor (motor6) to half power (50)
	//sleep(1000);										//Wait for 2 seconds before continuing on in the program.

	playNote(noteE, octave1, 20);
	playNote(noteE, octave1, 20);
	playNote(noteG, octave2, 20);
	playNote(noteC, octave3, 20);
	playNote(noteE, octave3, 20);
	sleep(20);
	playNote(noteE, octave3, 20);
	sleep(20);
	playNote(noteC, octave3, 20);
	sleep(40);
	playNote(noteC, octave1, 20);
	playNote(noteA, octave1, 20);
	playNote(noteA, octave1, 20);

	//while (true) {
	//	setMotorSpeed(leftMotor,  (getJoystickValue(ChA) + getJoystickValue(ChB))/2);  	// (y - x)/2
	//	setMotorSpeed(rightMotor, (getJoystickValue(ChA) - getJoystickValue(ChB))/2);  	// (y + x)/2
	//}
}
