//#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
//#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void playTheme() {
	playNote(noteE, octave1, 20);
	playNote(noteE, octave1, 20);
	playNote(noteG, octave2, 20);
	playNote(noteC, octave3, 20);
	playNote(noteE, octave3, 20);
	sleep(20);
	playNote(noteE, octave3, 20);
	sleep(20);
	playNote(noteC, octave3, 20);
	sleep(40);
	playNote(noteC, octave1, 20);
	playNote(noteA, octave1, 20);
	playNote(noteA, octave1, 20);
}

task main()
{
	playTheme();
	//while (true) {
	//	setMotorSpeed(leftMotor,  (getJoystickValue(ChA) + getJoystickValue(ChB))/2);  	// (y - x)/2
	//	setMotorSpeed(rightMotor, (getJoystickValue(ChA) - getJoystickValue(ChB))/2);  	// (y + x)/2
	//}
}
